include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    lines_longer_than_80_chars: true
    sort_pub_dependencies: true
    constant_identifier_names: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    strict_top_level_inference: ignore
    use_build_context_synchronously: ignore
