name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_lints: ^6.0.0
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^3.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  integration_test:
    sdk: flutter
  mockito: ^5.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificate/
