// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdI8SsrK74z_OhVrZ7tSsyGzCxOKiT_M',
    appId: '1:742701887299:web:974a5e3dfb7b732550c9f6',
    messagingSenderId: '742701887299',
    projectId: 'movie-dian',
    authDomain: 'movie-dian.firebaseapp.com',
    storageBucket: 'movie-dian.firebasestorage.app',
    measurementId: 'G-VJ7Q5Z82WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphU6VLLqojxoePaLPm6EtAEA7a71-Z6A',
    appId: '1:742701887299:android:b229733689ba26e150c9f6',
    messagingSenderId: '742701887299',
    projectId: 'movie-dian',
    storageBucket: 'movie-dian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDql87GsBQl0Gk6PtffV9DqaCbEyNUFtjI',
    appId: '1:742701887299:ios:b3dd6e59b82f9ebc50c9f6',
    messagingSenderId: '742701887299',
    projectId: 'movie-dian',
    storageBucket: 'movie-dian.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
